name: Add Word

on:
  workflow_dispatch:
    inputs:
      word:
        description: 'The word to add'
        required: true
        type: string
      date:
        description: 'Date to add the word to (YYYY-MM-DD). Leave empty for today.'
        required: false
        type: string
      overwrite:
        description: 'Overwrite existing word if one exists for the date'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  add-word:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Add word
        id: add_word
        run: |
          OVERWRITE_FLAG=""
          if [[ "${{ inputs.overwrite }}" == "true" ]]; then
            OVERWRITE_FLAG="--overwrite"
          fi
          if npm run tool:add-word -- ${{ inputs.word }} ${{ inputs.date || '' }} $OVERWRITE_FLAG; then
            echo "word_added=1" >> $GITHUB_OUTPUT
          else
            echo "word_added=0" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.add_word.outputs.word_added == '1'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        if: steps.add_word.outputs.word_added == '1'
        run: |
          git add src/data/words/
          git commit -m "Add word: ${{ inputs.word }}"
          git push origin ${{ github.ref }}
